### PR TITLE
    glib2: Use NUM2ULONG instead of NUM2UINT in GLib.format_size

### LINKED ISSUE #413: GLib2 GLib.format_size size to big to convert to unsigned int
When attempting to format sizes >= 4GB, GLib.format_size throws an exception that the integer is to big to convert to `unsigned int'.

Example:
```ruby
require 'glib2'

size = 4294967296 # 4 GBs 1024 * 1024 * 1024 * 4
puts "Size is: " + GLib.format_size(size)
```

GLib.format_size() should use uint64 or guint64, instead of uint or guint.

### PR DESCRIPTION
**Pull request by cosmo0920**
fixes #413

Because following RangeError exception is thrown when GLib.format_size(1000 * 1000 * 1000 * 5):

    ```log
    Error: test_5gb(TestGLibFileUtils::#format_size)
    : RangeError: integer 5000000000 too big to convert to `unsigned int'
    ruby-gnome2/glib2/test/test_file_utils.rb:34:in
    `format_size'
    ruby-gnome2/glib2/test/test_file_utils.rb:34:in
    `test_5gb'
         31:     end
         32:
         33:     def test_5gb
      => 34:       assert_equal("5.0 GB", GLib.format_size(1000 * 1000 * 1000 * 5))
         35:     end
         36:
         37:     sub_test_case "flags" do
    ```

### CODE REVIEW

File: glib2/test/test_file_utils.rb [hunk 1]
```diff
@@ -30,6 +30,10 @@ def test_gb
       assert_equal("1.0 GB", GLib.format_size(1000 * 1000 * 1000))
     end
 
+    def test_5gb
```
Comment (kou) [inline glib2/test/test_file_utils.rb]: It's better that test name means "guint32 over value".
Because "5" isn't important. "guint32 over value" is important.

File: glib2/ext/glib2/rbglib_fileutils.c [hunk 2]
```diff
@@ -53,7 +53,7 @@ void        g_dir_close                     (GDir *dir);
 static VALUE
 rbglib_m_format_size_for_display(G_GNUC_UNUSED VALUE self, VALUE size)
 {
-    return CSTR2RVAL_FREE(g_format_size_for_display(NUM2INT(size)));
+    return CSTR2RVAL_FREE(g_format_size_for_display(NUM2ULONG(size)));
```
Comment (kou) [inline glib2/ext/glib2/rbglib_fileutils.c]: A test is needed.

File: glib2/test/test_file_utils.rb [hunk 3]
```diff
@@ -30,6 +30,10 @@ def test_gb
       assert_equal("1.0 GB", GLib.format_size(1000 * 1000 * 1000))
     end
 
+    def test_over_guint32_value
+      assert_equal("5.0 GB", GLib.format_size(1000 * 1000 * 1000 * 5))
```
Comment (kou) [inline glib2/test/test_file_utils.rb]: Value should be `max uint32 value + 1`.

**Comment by cosmo0920** [comment]
Done!
I've added and rewrite tests.

File: glib2/test/test_file_utils.rb [hunk 4]
```diff
@@ -3,14 +3,26 @@
...
+    def test_1mb
+      assert_equal("1.0 MB", GLib.format_size_for_display(1024 * 1024))
+    end
+
+    def test_1gb
+      assert_equal("1.0 GB", GLib.format_size_for_display(1024 * 1024 * 1024))
+    end
+
+    def test_over_guint32_value
+      assert_equal("4.0 GB", GLib.format_size_for_display((2**32-1) + 1))
```
Comment (kou) [inline glib2/test/test_file_utils.rb]: Spaces are missing around operator.

Comment (kou) [inline glib2/test/test_file_utils.rb]: Name `2 ** 32 - 1`.

File: glib2/test/test_file_utils.rb [hunk 5]
```diff
@@ -3,14 +3,26 @@
...
+  sub_test_case "#format_size_for_display" do
+    def setup
+      only_glib_version(2, 16, 0)
+    end
+
+    def test_kb
+      assert_equal("1.0 KB", GLib.format_size_for_display(1024))
+    end
+
+    def test_1mb
```
Comment (kou) [inline glib2/test/test_file_utils.rb]: Is `1` needed?

File: glib2/test/test_file_utils.rb [hunk 6]
```diff
@@ -3,14 +3,26 @@
 class TestGLibFileUtils < Test::Unit::TestCase
   include GLibTestUtils
 
-  def test_format_size_for_display
-    only_glib_version(2, 16, 0)
-
-    assert_equal("1.0 KB", GLib.format_size_for_display(1024))
-    assert_equal("10.0 KB", GLib.format_size_for_display(1024 * 10))
```
Comment (kou) [inline glib2/test/test_file_utils.rb]: Why is this case removed?
Is the case needed for confirming unit (1000 or 1024)?

Comment (cosmo0920) [inline glib2/test/test_file_utils.rb]: Ah, I see....
I've readded a 10kb case for confirming unit.

File: glib2/ext/glib2/rbglib_fileutils.c (hunk 2 above)
Comment (cosmo0920) [inline glib2/ext/glib2/rbglib_fileutils.c]: I added this one: https://github.com/ruby-gnome2/ruby-gnome2/pull/414/files#diff-c70a30246e4ebcd1836b052da6f4af02R27.

**Comment by kou** [comment]
Merged!

**Comment by cosmo0920** [comment]
Thanks!

**Comment by eumario** [comment]
Thanks @cosmo0920, this was causing issues whenever I tried to format size of the total hard drive space, or total memory I had on my system, in the applet I'm creating.
